### ISSUE TITLE
Fix links broken by section heading changes

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#107]
I think some name format headings changed and may need to be updated. Some may just have been made incorrectly to begin with because I didn't understand docusaurus's way of making urls safe.

Procedure for making sure you have the right link text to an internal link:
1. Go to the heading you will want to link.
2. Look at your address bar.
3. Copy the part from `#` onwards
4. If you want to link from another page, use `[link text](file_name.md#text-that-was-in-the-url)`
5. If you want to link from within the same page, use just `[link text](#text-that-was-in-the-url)`

**Comment by BryceStevenWilley** [comment]
TIL that https://github.com/facebook/docusaurus/pull/3059 exists, and docusaurs warns you when internal links are broken. Neat. 

I think that this is good guide, but as an issue should be fixed? If we ever change internal headings, we'll know what internal links are broken, and TBH I don't think we need to be afraid of breaking other people's links to specific headings on our site. Gonna go ahead and close this.
