### ISSUE TITLE
AEM form flow - add to PDF editing page

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#113]
From bootcamp participant:
> Also, am testing a form created in AEM: Opened it in Acrobat and extracted all pages. Uploaded result successfully to Documate and Weaver. [...] definitely a helpful shortcut, esp for those multipage forms...

Not sure what this means, but maybe someone else does.

**Comment by BryceStevenWilley** [comment]
AEM apparently is [Adobe Experience Manager](https://business.adobe.com/products/experience-manager/adobe-experience-manager.html), whatever that means. 

I'd say low priority adding this suggestion, it's a business oriented tool, I don't much of our target audience would have access to it.

**Comment by nonprofittechy** [comment]
AEM is a tool that produces what we also call Adobe LiveCycle forms. This is already covered on the "Editing PDF" page.
