### ISSUE TITLE
GitHub docs: Add warning to avoid forking when collaborating on the same code

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#116]
Forking means someone will not be able to adjust your code in the playground and push back to the appropriate repo.

**Comment by BryceStevenWilley** [comment]
I'm actually not sure about this warning. Forking is a bit more advanced git/github knowledge than most people will have, but it is valid to ask people to fork and then only contribute to the main branch of the repo through a PR. That way all code that enters the main branch has to be reviewed.

**Comment by plocket** [comment]
Unless it's changed since I last tried it, it can be pretty annoying and obstructive to work with a PR from a fork in da. Not in general. In general forks can be great. In da it's been a problem in the past. I wish I could bring the details to mind so I could be more concrete about it.

**Comment by nonprofittechy** [comment]
Docassemble doesn't let you choose which "owner" of a repo with a shared name to send code to. Agreed that this is worth clarifying as a Docassemble/Assembly Line-specific GitHub usage.

**Comment by BryceStevenWilley** [comment]
Is it worth it to try to add this feature to Docassemble, letting you choose which org to make a repo under (or just to keep it personal)?

**Comment by samglover** [comment]
Closing now that we have an [updated GitHub workflow documentation page](https://assemblyline.suffolklitlab.org/docs/github).

**Comment by plocket** [comment]
The documentation doesn't mention anything about avoiding forking, so it doesn't address this particular issue.

**Comment by samglover** [comment]
OK, I see I wasn't appreciating the nature of the issue. I'll keep this open and check in with @plocket before I work on this to make sure I understand how to explain the problem with forking.
