### ISSUE TITLE
Fully port github documentation

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#12]

**Comment by BryceStevenWilley** [comment]
Is there more outside of https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/github.md?

**Comment by plocket** [comment]
The link that's at the top of github.md pointing to the original doc can help: https://docs.google.com/document/d/1pj1DFIhzzwB6raeCytnmPSR41WfNvG-T9GYPsf1wOsA. I deliberately replaced some sections that were better covered with GitHubs own docs, but there are still images and pieces of content to move in. It might also be worth incorporating stuff from comments.

Sorry, this was part of brainstorming some issues, so it didn't get the full treatment with links.
