### ISSUE TITLE
Create a interview that would act as a good MVP example

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#126]
> If there's something simple and safe, it shouldn't be too hard to get it into MVP form.

MOTION TO WAIVE ATTENDANCE AT PARENT EDUCATION PROGRAM
[cjd-444-motion-to-waive-attend-parent-ed-program_0.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/5282650/cjd-444-motion-to-waive-attend-parent-ed-program_0.pdf)

**Comment by nonprofittechy** [comment]
Actually now that I think about it more, the purpose might have been to literally demonstrate what an MVP form is, so people knew when their form was "good enough". This is partially addressed in the [maturity model](https://suffolklitlab.org/legal-tech-class/docs/legal-tech-overview/maturity-model)

**Comment by nonprofittechy** [comment]
This doesn't actually feel very actionable as I'm reviewing it now. @plocket do you remember anything more about it? Tempted to close but will leave it up to you.

Where would we link to this form from? Does it need to stay static at MVP level forever?
