### ISSUE TITLE
Look into setting up Pydoc => Docusaurus v2 workflow

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#127]
Improve docstrings to match

**Comment by nonprofittechy** [comment]
Another alternative is sphinx--which powers readthedocs.io

**Comment by nonprofittechy** [comment]
We may need to add better pydoc-style documentation for parameters. Also, we may need to add documentation to the __init__.py

see: https://stackoverflow.com/questions/13040646/how-do-i-create-documentation-with-pydoc

**Comment by nonprofittechy** [comment]
https://github.com/NiklasRosenstein/pydoc-markdown/tree/develop/examples/docusaurus/docusaurus-example

and see https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/tree/pydoc_experiment

**Comment by nonprofittechy** [comment]
Basic setup steps:

1. pip install pydoc-markdown
2. clone suffolklitlab/docassemble-assemblyline
3. clone suffolklitlab/docassemble-AssemblyLine-documentation
4. run pydoc-markdown

Relevant configuration:

see `pydoc-markdown.yml` to change paths, etc.

running pydoc-markdown generates files into this folder: `docs/reference/`.

Edited sidebar.js to import the `docs/reference/sidebar.json` file into the main sidebar.js.

**Comment by nonprofittechy** [comment]
At sprint review today 5/24/21 we discussed that this might be integrated either into the bump version script (@BryceStevenWilley ) or into a Github action (@plocket). Whoever decides to take on: please assign yourself and for this sprint, just get a first version in w/o the automation.

I believe @plocket was willing to research alternative docstring formats. To my knowledge the popular options are:

1. Sphinx (looks like it comes with a vs code plugin): https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html
2. Google https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy

See the docs here: https://pydoc-markdown.readthedocs.io/en/latest/docs/api-documentation/processors/

**Comment by plocket** [comment]
Something about my paths is messed up or something and I can't get pydoc-markdown to run, but I'll make a branch with an edit for the only thing that seems to be creating an error for me currently.

**Comment by plocket** [comment]
As per our meeting, we're just going to go with what we have for now and worry about improvements later.
