### ISSUE TITLE
Discuss: All checklists on a card at the very start, or add them as they progress?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#13]
Would love thoughts from the group

**Comment by BryceStevenWilley** [comment]
I think was decided as adding all at the start? I guess we'll heard some more feedback from people taking forms all the way through soon.

**Comment by nonprofittechy** [comment]
Closing this as the Trello checklists are pretty finalized now. I can see why it's posted here but it's not actionable as a documentation topic.
