### ISSUE TITLE
Organize the Documentation around Divio's Documentation Square

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine-documentation#131]
Longer term, we might want to organize the docs around the [divio documentation system](https://documentation.divio.com/), which splits documentation into 4 categories: tutorials, how-to guides, technical reference and explanation. We currently have two of those categories: tutorials and technical reference (the API reference).  

I feel like a lot of our (potential) content, like following plain language suggestions, trello boxes, using Github, etc, doesn't really fall into one of those categories cleanly. Parts sorta fall into each of those 4 boxes, or maybe fall into something else, more of a "Best-practices" section (you can't really make a tutorial or an API reference on best practices). But maybe that's fine. Right now there's just hunks of documentation that people need to get through, and breaking it up into smaller, action-oriented articles that are easily sized up, i.e. "I don't need to know the history of Trello and just-in-time systems right now, but understanding how to copy checklist around is great!".

**Comment by plocket** [comment]
Would love to include that link in our 'style guide' when we start using it.
