### ISSUE TITLE
Code practices: data structures for complex logic

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#15]
- Change questions you're asking
- Use values to access specific values in another dictionary possibly in combination with set math
- Set math in general
- Check against lists of values perhaps
- ...

**Comment by nonprofittechy** [comment]
Think this has a good start now: https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/coding_style_guide
