### ISSUE TITLE
Get feedback on ALDocument documentation

### ISSUE THREAD

**Issue by stevejaubz** [SuffolkLITLab/docassemble-AssemblyLine-documentation#150]
Current documentation is very technical and requires a deeper level of understanding than many have (myself included). More plain language or examples could be beneficial. 

Would benefit older interviews that need an updated next_steps.docx and be a good example to show

**Comment by stevejaubz** [comment]
Added next_steps in MTVHousing repo: https://github.com/SuffolkLITLab/docassemble-MTVHousing/tree/testing_feedback

**Comment by nonprofittechy** [comment]
I think this is a lot better now.
