### ISSUE TITLE
Bootcamp discussion

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#16]
Make sure there are issues for each of these that is not yet complete:

1. Read what Docassemble is. 
1. Do the Hello, World exercise. (Q textbook, video?) Video is at docacon.com 
1. Get up a page that lists what to do before the class starts. (does this go in documentation?) 

Things that need documentation (**bold is AL-specific main documentation stuff**): (Someone to create Github Issues as needed) https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/   

- **Overview of the project**
- **Field labels for PDFs and Docx**
- How to use Documate to label a PDF: documate have a video already?
  - **How to label a PDF** (seems like it would be a documate thing?)
- **How to use the wizard**
- **Copying our Trello template boards**
  - **How to use the Trello checklists**
- **Some Docassemble basics**
  - **Structure of the wizard YAML file**
  - Reordering questions
  - Adding show if
  - Adding branching logic
  - Using answers from radio buttons and checkboxes in your code
- Create a playground project
- Github
  - How to create your github account
  - Connect your github to docassemble playground
  - Pull a package into your playground
- **Customizing the AssemblyLine packages**
  - **How to customize the logo**
  - **How to customize CSS**
- **Using the docassemble.Income class**
- How to create a DAList of objects and gather items for a table
- How to install a package on your server and create a link to it

**Comment by plocket** [comment]
Issues made or item completed:
- [x] 1. Read what Docassemble is. 
- [x] 1. Do the Hello, World exercise. (Q textbook, video?) Video is at docacon.com 
- [x] 1. Get up a page that lists what to do before the class starts. (does this go in documentation?) 

Things that need documentation (**bold is AL-specific main documentation stuff**): (Someone to create Github Issues as needed) https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/   

- [ ] **Overview of the project**
- [ ] **Field labels for PDFs and Docx**
- [ ] How to use Documate to label a PDF: documate have a video already?
  - [ ] **How to label a PDF** (seems like it would be a documate thing?)
- [ ] **How to use the wizard**
- [ ] **Copying our Trello template boards**
  - [ ] **How to use the Trello checklists**
- [ ] **Some Docassemble basics**
  - [ ] **Structure of the wizard YAML file**
  - [ ] Reordering questions
  - [ ] Adding show if
  - [ ] Adding branching logic
  - [ ] Using answers from radio buttons and checkboxes in your code
- [ ] Create a playground project
- [ ] Github
  - [ ] How to create your github account
  - [ ] Connect your github to docassemble playground
  - [ ] Pull a package into your playground
- [ ] **Customizing the AssemblyLine packages**
  - [ ] **How to customize the logo**
  - [ ] **How to customize CSS**
- [ ] **Using the docassemble.Income class**
- [ ] How to create a DAList of objects and gather items for a table
- [ ] How to install a package on your server and create a link to it

**Comment by plocket** [comment]
Have made issues or completed everything on this list. New items will just be made into issues.

**Comment by BryceStevenWilley** [comment]
Github and it's sub checks should all be covered by https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/github.md. We do probably want to edit a lot of these pages, that we can handle that later.
