### ISSUE TITLE
Add clear labels for different audiences

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#165]
E.g., had a student who thought they had to install Docassemble to do their final project.

Have different "getting started" entry points for:

1. new assembly line startups
2. individual participants in the assembly line

**Comment by samglover** [comment]
Although this issue is a little outdated, I'm interpreting it as requesting onboarding and workflow documentation for interview builders, which seems very useful.

**Comment by samglover** [comment]
Partly completed by #457

**Comment by samglover** [comment]
With #459 I think the documentation now has entry points for beginners and advanced interview builders.
