### ISSUE TITLE
Add a page to document al_courts and MACourts

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#172]

**Comment by BryceStevenWilley** [comment]
Note: this is partially there: https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/reference/al_courts. If we improved the reference code with a few short examples, it might be good enough.

MACourts would still need a page.

**Comment by samglover** [comment]
Closing as duplicative of #308
