### ISSUE TITLE
Add live demo link and 2 new functions to the ALToolbox page

### ISSUE THREAD

**Issue by purplesky2016** [SuffolkLITLab/docassemble-AssemblyLine-documentation#180]
As discussed on the call today, we need to add some new additions to the ALToolbox page.

1. display_template()
2. phone number validation
3. ALToolbox overview page to run live demos

@nonprofittechy - I don't have the link for item 3, I think it probably should come from the prod server so that it's more stable. Also @plocket is reviewing item 2, whose reference file name may or may not change.

I'll make as many changes as I can, and let you guys finalize them.

**Comment by nonprofittechy** [comment]
Closed in #181
