### ISSUE TITLE
Error w/ deploy action

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#187]
@plocket no rush, but do you want to look at this when you have a chance?

https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/runs/4552454205?check_suite_focus=true

I was able to successfully deploy manually w/ no problem. Looks like a missing environment variable perhaps?

**Comment by nonprofittechy** [comment]
Probably a 1-off--subsequent deploys are working fine. feel free to close if all looks good to you

**Comment by plocket** [comment]
Yeah, this looks like a one-off 👍
