### ISSUE TITLE
Error with image links in /contributors page

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#188]
Bryce,

Do you want to look at the image references? I think you might need to mirror the way that I did them for the splash page. Those didn't work locally but I made them work in production. It would be nice to get it working in both places, but production is more important.

I'm also going to try upgrading to the newest Docusaurus as we are a few versions behind.

Edit: I upgraded to beta 2.00.13 and the image links didn't work on their own yet.

**Comment by BryceStevenWilley** [comment]
It's fixed in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/commit/731a094b39fcced845577b50734d9e2b9f263d1b. I had tried that the first time, but I assumed broken locally means it'd be broken on prod too, haha.

**Comment by nonprofittechy** [comment]
Good news! .13 fixes it when you run locally via npm run start
