### ISSUE TITLE
Add searching

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#2]
https://v2.docusaurus.io/docs/search/

This is something we need to apply for: https://docsearch.algolia.com/apply/. Do we want to do this? [Decision was yes]

☝️ @colarusso

**Comment by plocket** [comment]
Have requested an email to be connected to the search application.

**Comment by colarusso** [comment]
FWIW, I still waiting on an email.

**Comment by plocket** [comment]
Removing milestone as we don't have control over this.
