### ISSUE TITLE
How to normalize a PDF

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#20]
> some "normalization" process for a PDF would be good. (print to pdf, followed by some XPDF-like process).
> Converting Live Cycle PDF

Are those the same thing?

Some [conversation in the archives](https://courtformsonline.org/67283bsdfguwagrwi3rg48074grqfiwg7892yrwdhil2p98ry97gfgqy9qaewfkjlh239/slack_archive/assembly-line-code-questions.html#2020-12-16%2017:27:50) (summarized below): 

> - a "PdfReadError: could not find xref table at specified location" error in an interview
> - The pdf is fine locally, before uploading as a template (and after downloading it again).
> - some valid PDFs can't be read by pypdf
> - pretty sure from the error that xref table = cross reference table (internal bookmarks some PDFs have)
> - this thread suggests using QPDF to repair the xref table: https://stackoverflow.com/questions/46485766/could-not-find-x-ref-table-pdf/46501105
> - That seems to have worked.

**Comment by nonprofittechy** [comment]
Normal procedure would be just to print to PDF.

We could add some troubleshooting techniques but they shouldn't be used unless needed, I think.

1. Run through documate.org/PDF with "keep existing labels" option.
2. Use QPDF to see if it can fix the PDF
