### ISSUE TITLE
GitHub tutorials is not a top level concept

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#204]
Looking at this now and I'm not sure GitHub tutorials makes sense at the top level of our left navigation. It has a ton of useful content but it's more an appendix to the purpose of the site. Can we brainstorm a different place to put it?

I think probably there's a level equivalent to (maybe reorganizing) "Authoring your interview" or "Assembly Line Process" that this belongs under.

**Comment by plocket** [comment]
I was thinking that too the other day 👍
