### ISSUE TITLE
Document https://github.com/SuffolkLITLab/FormFyxer

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#219]
Should start documenting the functions in FormFyxer library

**Comment by BryceStevenWilley** [comment]
I'd say this is solved with https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/commit/8864581b1fc999fb1a545762b10bb9d295674902. We can consider more thorough guides later, but our focus should definitely be on ratemypdf over raw FormFyxer functions.
