### ISSUE TITLE
Add a page for ALRecipes

### ISSUE THREAD

**Issue by purplesky2016** [SuffolkLITLab/docassemble-AssemblyLine-documentation#223]
As discussed on the deep dive call.

To avoid redundancy, this page will only outline the repo's purpose and contents, but not list every recipe. It will link to the repo's landing page.

**Comment by purplesky2016** [comment]
It goes with https://github.com/SuffolkLITLab/docassemble-ALRecipes/pull/7

**Comment by samglover** [comment]
[This page exists.](https://assemblyline.suffolklitlab.org/docs/framework/alrecipes)
