### ISSUE TITLE
Add ALWeaver doc variable names overview

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#23]
Will edit this as needs appear.

Page already started for this: https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/doc_vars_overview.md

Overview should be more descriptive than the plain reference page that's currently up. The why's and explanation of the rules and ways to use things can be explained. Can probably base most of this off of stuff in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/document_variables.md

Other todos:
- [ ] Explanation of prefixes/objects (add link to this in reference doc)
- [ ] Explanation of suffixes/attributes (add link to this in reference doc)
- [ ] Add definition of reserved word (add link to this in reference doc)
- [ ] Add/move some of the 'Print a value in multiple places' explanation to overview doc (add link to this in reference doc)

**Comment by plocket** [comment]
It might be better to make this once we observer what questions people ask during the bootcamp.

**Comment by plocket** [comment]
Unnecessary for the bootcamp as those concepts can be explained in person.

**Comment by nonprofittechy** [comment]
I missed that this already existed when editing the documentation recently, but I think a lot of the ideas are captured in https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/label_variables. We may want to do an additional review and remove this so there are not two similar docs that are discoverable with the search function.
