### ISSUE TITLE
Check (add?) overview of the project

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#25]

**Comment by BryceStevenWilley** [comment]
I feel like this would be mostly from https://suffolklitlab.org/doc-assembly-line/?  Do we just want to link to that page from the intro, or do we want an entirely different page on this site?

**Comment by plocket** [comment]
This might also be a duplicate of #36 - this could go on the intro page. Also see #99 - what to do with the landing page.

**Comment by colarusso** [comment]
I realize I really like some of the language on the old page, may revisit, but we have an update in a PR with a nice video that should do for now.
