### ISSUE TITLE
Style guide question: do we want legal citations?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#259]
Working on making changes to the Petition to Enforce the Sanitary Code, and I think we should have a uniform style guide that addresses whether or not to link to the statute that enables a certain kind of motion, petition, or action. It sounds potentially helpful but also potentially confusing.

https://github.com/SuffolkLITLab/docassemble-SanitaryCode/

**Comment by samglover** [comment]
I think this is solved by the [expanded interview metadata block we are using for CourtFormsOnline](https://github.com/SuffolkLITLab/courtformsonline.org/issues/8), but that metadata needs to be documented, probably [here](https://assemblyline.suffolklitlab.org/docs/generated_yaml#metadata). Closing in favor of an issue along those lines.
