### ISSUE TITLE
Change document var names table columns into tabs?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#3]
So that people using PDFs just look at PDF-specific stuff and people using docx look at docx stuff. https://v2.docusaurus.io/docs/markdown-features/#tabs

**Comment by BryceStevenWilley** [comment]
Took a quick look at this, it should be probably be low priority unless we hear from actual people that the current layout is confusing. To add this, we'd have to double all of the current tables just to essentially change the header to say either "YAML" or "DOCX". Doesn't seem to be a way to just change the top row of the table with tabs.  Duplicating an entire table just to change a handful of words is going to be "bug"-prone when going back and trying to add or correct entries in these tables, and wrong documentation IMO is worse than slightly cumbersome documentation.

**Comment by plocket** [comment]
I agree. I was thinking we could do it with React, but a couple people commented that we should keep it as editable as possible (which makes sense). Without using React components, there would definitely be a ton of duplication.

**Comment by nonprofittechy** [comment]
New shortened format addresses this, I think. But we can always revisit. I actually don't mind using a few react components here at all where they add value.
