### ISSUE TITLE
Use native integration with mermaid

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#307]
As of the stable release of Docusaurus, we can now directly embed Mermaid diagrams. We have a few that are integrated as image links to the mermaid.js website, which is not a great workaround.

https://docusaurus.io/feature-requests/p/add-mermaid-support

We should migrate those, and consider whether any additional diagrams would be useful now that there's a better diagramming option.

**Comment by BryceStevenWilley** [comment]
Closing in favor of #258
