### ISSUE TITLE
Demo please for Shorthand function to display a checkbox in replace of a True/False boolean value in a DOCX template

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#316]
[Shorthand function to display a checkbox in replace of a True/False boolean value in a DOCX template](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/altoolbox#shorthand-function-to-display-a-checkbox-in-replace-of-a-truefalse-boolean-value-in-a-docx-template) is difficult to understand without a demo. 

Short of a demo, could we have some pictures that show where to put the code in the docx?

I have quite a few checkboxes so far in this Child Support Guidelines Affidavit form, note specifically the checkboxes for TANF below mother and father.  I would like to know how to use this function in [the docx template](https://docs.google.com/document/d/1aevcxSwEFnX2PVbNepi0q5Qe1y9WZMJO/edit?usp=share_link&ouid=113049012685525767628&rtpof=true&sd=true)
![image](https://user-images.githubusercontent.com/20183039/218791406-ede0ae98-e768-41c9-8336-2cfb52beb7bb.png)

**Comment by BryceStevenWilley** [comment]
I can write a quick section on this, with some photos.

For your specific doc, it somehow has [DOCX form fields](https://support.microsoft.com/en-us/office/create-forms-that-users-complete-or-print-in-word-040c5cc1-e309-445b-94ac-542f732c8c8b) inserted in it, which I haven't ever seen before. We definitely don't support them, though I'm curious what it would take to support something like that.

In the short term, I'd replace the checkboxes with `{{ output_checkbox(is_monthly) }}`. That is, backspace the checkboxes or select and delete, and then just put that text in the DOCX.
