### ISSUE TITLE
Point this at assemblyline.suffolklitlab.org

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#343]
Things to do:
- [x] Set up the new DNS
- [x] Edit the GitHub settings for this repo
- [x] Set up a dynamic redirect for the old URL

**Comment by samglover** [comment]
I suppose the URL should actually be documentassemblyline.suffolklitlab.org? Or perhaps docassemblyline.suffolklitlab.org?

**Comment by samglover** [comment]
> I suppose the URL should actually be documentassemblyline.suffolklitlab.org? Or perhaps docassemblyline.suffolklitlab.org?

It's longer, but I vote for documentassemblyline.suffolklitlab.org.

**Comment by samglover** [comment]
I think we've agreed on assemblyline.suffolklitlab.org.
