### ISSUE TITLE
Add (link to?) using the Income class? Improve docassemble docs?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#35]
There is [a bit of documentation](https://docassemble.org/docs/objects.html#Income), though not a lot. If it does need more documentation, maybe that should be made as a PR on docassemble documentation so it can be maintained there. Are there other reasons to keep it in our own documentation?

**Comment by nonprofittechy** [comment]
This isn't correct--we don't use the Docassemble "Income" class anywhere. It's the GBLS version we use. https://github.com/gbls/docassemble-income
