### ISSUE TITLE
Add to intro: continuing support/get involved resources

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#36]
- [ ] our standups
- [ ] Teaching Tuesday
- [ ] Docassemble Slack

**Comment by plocket** [comment]
Could you speak to the first two, @colarusso ? As to how people should get in. Should we go ahead and make a form for that?

**Comment by plocket** [comment]
See b024cc5 for a start to this

**Comment by colarusso** [comment]
I've edited the intro and suggested emailing the mass access email as the single act to get folks connected with the team.
