### ISSUE TITLE
Add week 4 resources links

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#37]
Note: the link to the second one is in the trello cards

- [ ] How to create a DAList of objects and gather items for a table
- [ ] How to install a package on your server and create a link to it (link in trello cards)

**Comment by nonprofittechy** [comment]
I'm not sure this is still in scope since it is not Assembly Line specific. Worth reconsidering how/where to link, maybe on the "customizing your interview" page as a common topic?
