### ISSUE TITLE
Style: DOCX or docx?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#4]

**Comment by nonprofittechy** [comment]
I think we're really inconsistent, but judging on what others have done, either `DOCX` or `.docx` seem to be acceptable, but not `docx` standalone. It's like XML.

**Comment by plocket** [comment]
Created as #5, though I need to update to make it clear that it's meant to be added to style guide documentation.

**Comment by nonprofittechy** [comment]
Yet another (maybe clearer) option: `Microsoft Word (.docx)`
