### ISSUE TITLE
Link the PDF/DOCX form we plan to use in the Bootcamp here so that the generated YAML can be explained

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#40]
Related to #30, showing the structure of the ALWeave generated YAML.

**Comment by plocket** [comment]
PDF: https://github.com/SuffolkLITLab/docassemble-GenericMotionFamilyLaw/blob/master/docassemble/GenericMotionFamilyLaw/data/templates/Generic_Motion_Family_Law_re-labeled.pdf

No current DOCX, but here's an example DOCX from the meeting: https://github.com/SuffolkLITLab/docassemble-MotionToSingleJusticeAppeals/blob/main/docassemble/MotionToSingleJusticeAppeals/data/templates/231_118_Suffolk_Lab_template_appeals.docx

**Comment by colarusso** [comment]
It looks like the links to the Generic Family Law motion have been added to the Label Variables Quick Reference. So is this settled?

**Comment by plocket** [comment]
Maybe I meant on the bootcamp page? I'm not sure what I meant by 'here'. I think it would be good to have them on the bootcamp page, though. Once you feel they're where they need to be, feel free to close the issue.

**Comment by plocket** [comment]
I'm loathe to edit the bootcamp page and this was really for week 1, so I'm closing this issue.
