### ISSUE TITLE
ALKiln: Organize a quick start page for students/help people who just want to write tests and don't need to know about setup

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#400]

**Comment by plocket** [comment]
A first go at a basic outline:

1. Run the interview
1. Note the page id on the last page
1. Tap "Share"
1. Download the interview's file
1. Go to https://plocket.github.io/al_story
1. Upload the interview's file to the field on that page
1. Fill in the fields:
    1. File description
    1. Scenario description
    1. ID of the final page
1. Download the al_story generated test file
1. Upload the test file to the "Sources" folder in the package
1. Give the test file a useful name
1. Save it

**Comment by plocket** [comment]
[These are the instructions in the docs](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/alkiln/writing/#alkiln_story). There are links to that section in other parts of the documentation. They don't include instructions on AL's JSON download button. I wasn't sure how to describe that clearly enough. Feel free to re-open if this needs adjustment.
