### ISSUE TITLE
Make sure Trello Information is maintained in here

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine-documentation#402]
Recently got this email from Trello:

>  A few changes are coming to your free Workspace, MassAccess. Free Workspaces will soon be limited to 10 collaborators, which includes members, guests, and pending invitations. This workspace currently has 10 or more collaborators.
>
>   On April 8, 2024, in free Workspaces at or over the limit, you’ll only be able to share boards with current Workspace collaborators.
>   On May 20, 2024, in free Workspaces over the limit, boards will become view only.
>
> To see and manage Workspace collaborators, including members, guests, and pending invitations, go to Workspace settings. 

I don't think anyone's used the MassAccess trello boards that much since our volunteer count dropped (last activity on boards that wasn't me: Pre-processing: Dec 1, 2021 at 7:13 PM, Development: Sep 13, 2022 at 3:21 PM, Testing: Dec 10, 2021 at 10:43 AM). But there is a ton of useful checklists and potential chores that we've mentioned trying to automate or continually do ourselves. Not a huge rush, since it looks like the workspaces will remain view only, but we will have to move things off of there eventually.

**Comment by samglover** [comment]
Thanks for passing this along! I'll preserve these checklists as I organize the workflow for future projects.

It looks like the cards on [this board](https://trello.com/b/TLXUvTFb/1-assembly-line-bootcamp-pre-processing) (and also [this card](https://trello.com/c/gMRECXb8/1-generic-motion-family-law)) have the full workflow.

**Comment by samglover** [comment]
I've archived this information elsewhere. It will live on in future workflows—with updates—so I am going to close this issue.
