### ISSUE TITLE
Global current section indicator style

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-AssemblyLine-documentation#408]
By default Docusaurus uses the hover color in the right sidebar index to indicate the current section. This is hard to see. @plocket tried adding underlining on the ALKiln documentation pages ([this page](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/alkiln/#story-tables), for example), which works great. Before we commit to one for the entire site it's worth considering other options for highlighting current pages. Perhaps a caret indicator or boldface?

*Note: this should wait until this repo is updated to Docusaurus 3.*

**Comment by plocket** [comment]
Example of using an arrow icon to indicate a user's current location in the table of contents:

<img width="169" alt="sidebar_arrow" src="https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/assets/52798256/a7a59ea6-701f-4ceb-9a36-1de18d8af2a4">

This might not be quite the right issue, but I wonder if using the offset underlines, as they now are at the link you included, when hovering over a table of contents item might be useful. Not absolutely crucial for us at the moment, but maybe more accessible:

<img width="205" alt="lower_underline" src="https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/assets/52798256/e350dbe4-5a87-451d-93d5-d8475bf39ce8">
