### ISSUE TITLE
Accessible link styles

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#413]
Currently our links don't have an underline when the user isn't interacting with them (hovering or clicking). They're just a slightly different color from the text. I personally have trouble telling the difference sometimes. If we want to change that, here is a sample of what a thin link offset underline for an inactive link might look like:

<img width="264" alt="inactive_link_underline" src="https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/assets/52798256/03626534-c90c-4448-a0ea-898afff888ca">

**Comment by nonprofittechy** [comment]
Agree with this change--links should be underlined as a basic accessibility choice.
