### ISSUE TITLE
Merge the API docs; get rid of the 01 naming convention

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine-documentation#419]
This will need some tweaks to how we use pymarkdown, but see:

https://docusaurus.io/docs/markdown-features/react#importing-markdown

![image](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/assets/7645641/031738c6-e07d-4a54-915f-cfc848f03c29)

**Comment by samglover** [comment]
I agree. This was a short-term fix for duplicate page/file names.

This is sort-of related to #415, as well.

**Comment by samglover** [comment]
FYI: the pages under `/reference` are auto-generated using the [pydoc-markdown.yml](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/pydoc-markdown.yml) template.
