### ISSUE TITLE
Add page for very basic ALDocument classes/functionality

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#42]
Not sure it's appropriate for the first week of bootcamp, but the breakdown of the structure of the YAML (#30) partially involves ALDocument, so some basic explanation could be really helpful.

**Comment by plocket** [comment]
What milestone is this most appropriate for @colarusso ?

**Comment by BryceStevenWilley** [comment]
#129 actually solves this too! Going to close for now
