### ISSUE TITLE
Update the Contributors page

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-AssemblyLine-documentation#428]
The [Contributors page](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/contributors.mdx) has not been updated in 3 years. I think it might make sense to convert this to a text-only directory and feature active court and org partners, interview builders, and backend developers with links to their online portals and GitHub repos.

**Comment by BryceStevenWilley** [comment]
Duplicate of #438, which I think has a more detailed plan of what to do with that page.

**Comment by samglover** [comment]
Haha I duplicated my own issue. SMH … closing.
