### ISSUE TITLE
Update the GitHub workflow documentation

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-AssemblyLine-documentation#461]
- [x] Add an example of a good pull request description to [Best Practices / Pull Requests](https://assemblyline.suffolklitlab.org/docs/github#branches-pull-requests-and-commits).
- [x] Document responsibilities: PR submitter’s job to make sure the code works. Reviewer’s job to review the code and comment/approve/request changes. If interview maintainer, they merge. Otherwise, PR submitter merges. From @plocket:

  > The "PR reviewer" section said that the PR maker should have included instructions about how to test their changes. Why not tell the PR maker that they should include instructions about how their changes should be tested.
[This is the comment I'm referring to](https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/447#discussion_r1651027109).
- [x] Explain the Install package on this server also option. (Installs it for all users on the server. Sounds useful but generally just causes problems. It’s better if everyone pulls manually when they want it.)
- [x] As a general rule, close issues with pull requests

**Comment by nonprofittechy** [comment]
We should also consider making some pull request templates here

**Comment by samglover** [comment]
Also, create a brief set of guidelines for decisionmakers and key stakeholders who want to use GitHub for answering questions.

**Comment by samglover** [comment]
Add this video: https://youtu.be/4j7rRRvsbfY
