### ISSUE TITLE
Add to docs style guide: Use DOCX more consistently

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#5]
`.docx` is also acceptable, but better to be consistent. Definitely avoid `docx`.

**Comment by plocket** [comment]
#4:
> Yet another (maybe clearer) option: `Microsoft Word (.docx)`

**Comment by nonprofittechy** [comment]
Perhaps we should use `Microsoft Word (.docx)` the first time it's mentioned in the documentation, and then `DOCX` thereafter. .docx works but is a little awkward.
