### ISSUE TITLE
comment on what our custom CSS is doing

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#56]
Saying this as someone who knows no CSS: is it worth it to comment what our custom CSS is doing?

_Originally posted by @BryceStevenWilley in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/46#discussion_r571058669_

**Comment by nonprofittechy** [comment]
Going to close this, but agreed that where a feature can be customized by CSS we should at least link to the CSS file it references. See e.g., links to aldocument.css here: https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/aldocument#using-the-download_list_html-method
