### ISSUE TITLE
Final: Update wizard reserved names when wizard prep work is done. Check global_constants for changes.

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#60]

**Comment by BryceStevenWilley** [comment]
I this also is closed by https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/commit/36ae54608a4326f3d944b7d3ed8e1c4059adea21#diff-7521963a9bbf9d38b03fa4089b841cca182310521c818b4a2bea0264a622f2d8R66 and #68, but I'm not super sure from the description here.

**Comment by plocket** [comment]
I think there might also need to be updates for `phone_number` and maybe a couple other small things, but I'm not completely sure.
