### ISSUE TITLE
Does the weaver handle things that are not in global constants?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#68]

**Comment by BryceStevenWilley** [comment]
> [Yesterday 1:39 PM] Quinten Steenhuis
    From dates, I think maybe you mean: does the wizard transform any pdf variable names that aren't listed in the global constants file?
> I don't think dates count as being transformed, we just use that as a hint for datatype. _yes and _no variables do get transformed in the current wizard release

**Comment by plocket** [comment]
Didn't spot that answer, thank you! That means we need to add those two the documentation. We may need more details:
1. `_date` triggers the field datatype `date`
2. `_yes` and `_no` trigger... a single checkbox? And the vars, I assume, get transformed into a single var?  @BryceStevenWilley (I can look it up later if needed).

Still to answer: Do we handle the `_day_month_year` type of stuff that we had listed in the previous documentation?

**Comment by BryceStevenWilley** [comment]
Trying to handle this now: where do we want this documented? https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/blob/main/docs/weaver_overview.md

**Comment by BryceStevenWilley** [comment]
Wait, nm, I think you fixed this already in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/commit/36ae54608a4326f3d944b7d3ed8e1c4059adea21#diff-7521963a9bbf9d38b03fa4089b841cca182310521c818b4a2bea0264a622f2d8R66. Sorry for dropping the ball on this. I think this issue is good for now. Going to close it.

**Comment by plocket** [comment]
No worries, I should have assigned myself first. I also wasn't sure if I had covered everything that was handled outside of constants, so I'm glad to have had a second eye on this.
