### ISSUE TITLE
Before developer starts any interview - Learn about the form

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#71]
Although we have various required information that require some knowledge of the particular form a developer is going to develop, I think it's possible to provide all that information without really understanding the context of a form - 
I would include in one of the initial checklists something like, read about the form and give the link  you used for context. Start with local lawhelp website , try courts, local gov site, FindLaw or NOLO. 
Perhaps add to the required information in the description, "Where can I learn more about how this form is used?"

**Comment by plocket** [comment]
☝️ Any details to add to this, @colarusso ? Where to insert this checklist or checklist item?

**Comment by plocket** [comment]
Eh, I'm just tired. I'll put it somewhere near the top and someone can review it later.

**Comment by plocket** [comment]
Review in description and checklist 1.1

**Comment by plocket** [comment]
This was approved.
