### ISSUE TITLE
Add "how to merge your branch with changes from main or another branch" to the GitHub documentation

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#74]

**Comment by BryceStevenWilley** [comment]
Found a good Twitter thread that does exactly this for us: https://twitter.com/theavalkyrie/status/1359378767802687490. We could def borrow the format and cite the tweet. 

That being said, if most people are starting from new repos, isn't Github's default branch main now, so they won't have to change things?

**Comment by plocket** [comment]
Changed the title to clarify the purpose. Let me know if that change clarifies the purpose: "Add GitHub section on updating a child branch to changes in parent"

**Comment by nonprofittechy** [comment]
This feels a bit out of scope. But worth revisiting if we find more intensive use of the GitHub features in our new/temporary team members.
