### ISSUE TITLE
Checklist item in 2.9 "Come to understand how interview can help or block..."

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#76]
Come to understand how this interview can help or block someone using this interview.
This isn't direction isn't very clear. 
Actually as I write up this issue, I am not even sure I understand what I am supposed to do as developer. 

I think the action needs to be more concrete and explicit and like explain or describe in the description of the card... but then I am not sure what it is - if we need this instruction, it needs to be clearer.

**Comment by plocket** [comment]
I think we'll just delete this item for now. It was meant to express too much. Feel free to re-open this if needed.
