### ISSUE TITLE
Checklist 2.9 Plain Language Review - is iterative

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine-documentation#77]
So just as developer circles round and round with SME the developer needs to circle round and round with Plain Language review. If SME adds more language, Plain Language reviewer needs to be able to review. 

Only remove Plain Language Reviewer from card after SME has checked that Plain language is satisfactory and SME has no more suggestions.

**Comment by plocket** [comment]
Adjusted the final items in the card. If/when you have time, would love your feedback on those changes, thank you!

**Comment by plocket** [comment]
Reviewed and current items are satisfactory.
