### ISSUE TITLE
New structure for docs

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#85]
Trying to remember we really don't want to duplicate what's going on in the Trello checklists.

# Current
- Intro
- Bootcamp
- Name formats
- PDFs and DOCXs
   - Editing PDFs
   - Label Variables
   - Generating Code
   - Anatomy of the YAML
- Github
- Docs Style Guide

# Proposal 1 for minimal week 1 structure
- About Us (Get Involved? About AssemblyLine. Maybe this all should be on the front page)
- Bootcamp
- Get Started (Trello, checklists, maturity model, MVP) ('bootcamp' may replace this)
- Generate code (Prepare? Use Documents?)
   - Overview (Broad generating steps)
   - Tools to Edit PDFs (useful general knowledge so out here? Or in 'generating code'?) [(How to make clear that this doc is separate from labels and var names?)]
   - Add Labels and Variables (should the detailed explanation of the inner workings be at the bottom or on its own page? Should this be a subsection?) [(Prepare your document?)]
   - Anatomy of the YAML (the generated YAML) [(Understand the Result? Understand the generated code? Use the generated code)]
- Github
- Name formats
- Documentation Style Guide

# Proposal 1 for eventual structure [(Old. See above edits for some things.)]
- About Us (Get Involved? About AssemblyLine)
- Bootcamp
- Getting Started (Trello, checklists, maturity model, MVP) ('bootcamp' may replace this)
- Generating code
   - Overview (of whole code generating flow, full of links to 'editing pdfs' page, pdf checker, and other key areas below and elsewhere)
   - Editing PDFs (useful general knowledge so out here? Or in 'generating code'?) [(How to make clear that this doc is separate from labels and var names?)]
   - Labels and Variables (should the detailed explanation of the inner workings be at the bottom or on its own page? Should this be a subsection?)
   - Code Generator
   - Anatomy of the YAML (the generated YAML)
- Content Guidance (Readability? Usability? Design? Interview Content Guidance? Plain Language and Content? What would perk people's ears up?)
- Code Style Guide
- Automated Testing
- Reference Material
   - Github
   - Code Troubleshooting
   - Name formats
- Documentation Style Guide

There's a fundamental conflict between having categories that are too broad and having too many pages.

Should we have a 'how to use this/about this documentation'?

**Comment by plocket** [comment]
Concepts to cover so maybe we can put them on index cards and rearrange them (will edit to add):

1. Very brief overview of whole process with lots of links
1. Create a docassemble server
1. Configure the server
1. Add developers to the server
1. Enable GitHub for the server
1. Add the AssemblyLine package to your server
1. Copy the Trello checklist boards for the organization
2. Get added to the server as a developer
2. Developer github stuff
1. Trello cards, checklists overview and rationale for why we did things the way we did them
1. MVP
2. Maturity model
3. Language and content guides
4. Coding conventions/style/thoughts
2. API for AL in general
5. Coding FAQ (including Troubleshooting code)
1. Prepare a PDF or DOCX - tools, how prefixes/suffixes work, variable name reference
1. Generate the initial code (how and Anatomy of generated YAML)
1. Edit the interview
1. Get reviews
1. Submit it for provisional approval (provisional on testing)
1. Manual tests
2. Automated tests
1. Deploy the interview
2. Documentation style guide/rationales
2. Future development and maybe other advanced topics
3. Resources page? With lots of links? Seems redundant.

**Comment by plocket** [comment]
Week 1 milestone was completed, so removing that milestone.

**Comment by nonprofittechy** [comment]
I took my own pass at this. Closing for now but there's great stuff to consider for future reorgs.
