### ISSUE TITLE
Trello process: Should people remove themselves from a card when they put it in a buffer?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#87]
That's what [previous documentation](https://docs.google.com/document/d/1bgT2GBGZrENlrQ5uugY_3GFpeqmt1urHYNCuqCYuATw/edit#heading=h.3ritjg8ryu1l) described, but it's not reflected in the checklists.

**Comment by colarusso** [comment]
I think that's an echo of how we thought things would work before we got a good amount of experience. Current practice is that the folks will stick with a card through most of it's journey. So no. We shouldn't suggest this.
