### ISSUE TITLE
Discuss deploying with push to main

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#93]
Docusaurus 2 docs: https://v2.docusaurus.io/docs/deployment/#triggering-deployment-with-github-actions

**Comment by nonprofittechy** [comment]
Sounds like a great idea to setup. @plocket any interest in taking that on? you've done most w/ Github actions already? no pressure though, current deployment is scalable for our update frequency
