### ISSUE TITLE
Should the weaver reference doc describe all 4 different names that variables can get?

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#94]
Example, I think, [from what was discussed in #188]:
| | Block | name example | address example |
|-|-|-|-|
| 0 | pdf | parent2_name | parent2_address_line_one |
| 1 | interview order | parents.gather() | parents[1].address.address |
| 2 | attachment block | parents[1] | parents[1].address.line_one() |
| 3 | question block | parents[1].name.first | parents[1].address.address |
| 4 | review screen display | parents[1] | parents[1].address.block() |
| 5 | review screen trigger | parents[1].name.first | parents[1].address.address |

[Edited]
Rows 3 and 5 are always the same as each other. Otherwise, all rows can be different than each other. (row 0 is the source and not something we have to worry about creating).

Also discussed - whether we use mapping or OOP, what we might want to try to do is:
1. See if it's possible to clarify the function names a bit
2. Move some of the composing that's going on outside the functions to inside the functions

_Originally posted by @plocket in https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/178#issuecomment-777708840_

**Comment by nonprofittechy** [comment]
The old format was a bit hard to read from experience using it in my class. I think this is a bit more usable now.
