### ISSUE TITLE
Decision: Use docassemble Stackoverflow as persistent knowledge base for people who are using AssemblyLine

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#96]
It's one of the things that I feel docassemble lacks. Some kind of forum? Maybe we could just make one for docassemble and include discussions about AssemblyLine in there. The only thing I tend to use out there is Stackoverflow. I do feel like da could use its own Stackoverflow, but that's a whole process. Other ideas:
- [Discourse](https://www.discourse.org/) - personally I don't like it, but I can't articulate why
- [Reddit](https://www.reddit.com/)

Cons:
- Would there be an issue with people coming to ask for legal help? I feel like there are places that already exist for that.
- How much moderation would be needed?

**Comment by BryceStevenWilley** [comment]
Just seeing this now, sorry. 

I feel like we should distinguish between knowledge bases like StackOverflow, and community sites, which I would categorize both Reddit and Discourse as (even though they show up in Google searches, which is what I think you mean by knowledge bases?). IMO, community sites for smaller projects like ours (a subset of Docassemble, which is a subset of legal tech, which is a subset of Webdev) work best when there's fewer of them, and the Teams site that we have already a good community site.

Now that docassemble does have it's own StackOverflow tag though, I think that's the best place to put AssemblyLine specific questions for a knowledge base.

**Comment by plocket** [comment]
That sounds like a good conclusion to me 👍
