### ISSUE TITLE
Document variables reference page: When we make the DOCX column more distinct, show Jinja syntax in tables

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#98]

**Comment by nonprofittechy** [comment]
https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/docx#docx-field-labels-are-just-typed-in I think addresses this clearly enough--worry that adding the `{{ }}` would clutter this. But could revisit later.
