### ISSUE TITLE
Discuss: Route straight to docs and remove landing page

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#99]
Alternatively, put intro content on landing page instead? The landing page isn't doing much for us right now.

**Comment by colarusso** [comment]
I agree we should just remove the landing page and go right to the intro.

**Comment by plocket** [comment]
Hint for that: https://v2.docusaurus.io/docs/docs-introduction/#docs-only-mode
